export default [
  {
    id: 1,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 2,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 3,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 4,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 5,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 6,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 7,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 8,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 9,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
  {
    id: 10,
    title: 'Write and edit simple documents',
    icon: 'textFile',
    completedActivities: '0',
    totalActivities: '8',
    level: '2',
    color: 'teal',
  },
];
