language: node_js

node_js: 
  - 12
cache:
  directories:
    - node_modules

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres

script:
  - npm run cover
  - npm run report-coverage
  
  